listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=NO
dirmessage_enable=YES
local_umask=022
# Banner que delata la versión (para que nmap/searchsploit lo identifiquen):
ftpd_banner=(vsFTPd 2.3.4)
# vsftpd en contenedor necesita esto o aborta por seccomp:
seccomp_sandbox=NO
pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
background=NO
