server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    # A propósito se dejan protocolos antiguos habilitados para que sslscan
    # tenga algo que marcar como inseguro en el laboratorio.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;
}
